apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-replicated-twice
  name: nginx-replicated-twice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-replicated-twice
  strategy:
    # The strategy Recreate deletes all pods at the same time and recreates new ones (when the image is updated)
    # Using RollingUpdate allows to gradually scale up/down (use maxUnavailable and maxSurge) 
    type: Recreate 
  template:
    metadata:
      labels:
        app: nginx-replicated-twice
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
